### ISSUE TITLE
Fix OpenAI Errors

### ISSUE THREAD

**Issue by krrishdholakia** [Najmul190/Discord-AI-Selfbot#10]
**Is your feature request related to a problem? Please describe.**
Hitting OpenAI rate limiting + context window errors

**Describe the solution you'd like**
Try using a library like `reliabilityGPT` to handle this - it'll do retries / model switching / etc. for you 

```
from reliablegpt import reliableGPT
openai.ChatCompletion.create = reliableGPT(openai.ChatCompletion.create, ...)
```

Source: https://github.com/BerriAI/reliableGPT

**Comment by krrishdholakia** [comment]
cc: @Najmul190

**Comment by Najmul190** [comment]
guessing this is just an ad, because I don't even use OpenAI properly within the code
