### ISSUE TITLE
[BUG] File "main.py", line 86, in generate_response

### ISSUE THREAD

**Issue by meowsynth** [Najmul190/Discord-AI-Selfbot#17]
I downloaded your repository, installed dependencies via bat file, wrote my promt in instructions, wrote channel in channels.txt, wrote my token and word trigger
I tried to get some kind of response by replying to my message, but the bot gives an error in the console and doesn't respond, on the default settings from the repository everything worked a week ago when testing, but when I wrote my promt and my trigger words it stopped working.

<img width="678" alt="image" src="https://github.com/Najmul190/Discord-AI-Selfbot/assets/70239765/92856d25-34a0-4400-bffe-cdde3f15b43d">
<img width="283" alt="image" src="https://github.com/Najmul190/Discord-AI-Selfbot/assets/70239765/8035869d-2b7d-4a1a-9cbd-f2ea8782f07a">

 - OS: Windows 11 last version, python 3.11
"
AI Selfbot successfully logged in as 9w8.
Task exception was never retrieved
future: <Task finished name='Task-55' coro=<on_message.<locals>.generate_response_in_thread() done, defined at main.py:252> exception=KeyError('choices')>
Traceback (most recent call last):
  File "main.py", line 253, in generate_response_in_thread
    response = await generate_response(prompt, history)
  File "main.py", line 86, in generate_response
    choices = response_data["choices"]
KeyError: 'choices'"

my discord id: 9w8
btw, if you can help...

**Comment by Najmul190** [comment]
This should now be fixed, make sure to update to the latest version.
