### ISSUE TITLE
[BUG] Google Bard Cookie

### ISSUE THREAD

**Issue by pnydiffuser** [Najmul190/Discord-AI-Selfbot#19]
**Describe the bug**
The Bard cookie does not work even after login from a different browser

**To Reproduce**
1. Git cloned repository, put info in .env and made a python venv
2. pip install -r requirements.txt and then python main.py
3. Bard cookie not set or has expired, so only ChatGPT will be available.

**Expected behavior**
The AI Selfbot to use Google Bard cookie alongside GPT

![aiselfbot1](https://github.com/Najmul190/Discord-AI-Selfbot/assets/131926673/327ec4fe-88d3-434e-a780-8ecca0ca4716)

**Desktop (please complete the following information):**
 - OS: arch linux

**Comment by redbaron2k7** [comment]
Unable to reproduce, worked fine for me after signing into a guest browser

**Comment by pnydiffuser** [comment]
> Unable to reproduce, worked fine for me after signing into a guest browser

That worked many thanks! Guest mode fixed my Cookie issue :1st_place_medal:
