### ISSUE TITLE
[BUG]AttributeError: 'NoneType' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by DHstun** [Najmul190/Discord-AI-Selfbot#21]
![iaaaamage](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/20851c9e-3fe0-4f8e-bcff-d26a7fb63bcb)

**Comment by Najmul190** [comment]
Fixed, just replace main.py.

**Comment by DHstun** [comment]
still the same error
![изображение_2023-08-13_123229656](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/4b5884ea-8a17-4c1f-81e4-e6e99a7f2c36)

**Comment by DHstun** [comment]
AttributeError: 'NoneType' object has no attribute 'splitlines'
Error making the request: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://gpt4.xunika.uk/api/openai/v1/chat/completions')
Task exception was never retrieved
future: <Task finished name='Task-50' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\dhstun\Desktop\Discord-AI-Selfbot-main (4)\Discord-AI-Selfbot-main\main.py:253> exception=AttributeError("'NoneType' object has no attribute 'splitlines'")>
Traceback (most recent call last):
  File "C:\Users\dhstun\Desktop\Discord-AI-Selfbot-main (4)\Discord-AI-Selfbot-main\main.py", line 256, in generate_response_in_thread
    chunks = split_response(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dhstun\Desktop\Discord-AI-Selfbot-main (4)\Discord-AI-Selfbot-main\main.py", line 95, in split_response
    lines = response.splitlines()
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'
