### ISSUE TITLE
[BUG]AttributeError: 'NoneType' object has no attribute 'splitlines' 

### ISSUE THREAD

**Issue by DHstun** [Najmul190/Discord-AI-Selfbot#22]
**Describe the bug**
AttributeError: 'NoneType' object has no attribute 'splitlines'
~imagine etc still works but bot cant talk

**Desktop (please complete the following information):**
 - Windows 10 (python 3.11)

**Additional context**
You said you fixed that but i still get that error
![изображение_2023-08-13_124547972](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/3354e819-9376-4e6f-bd6d-4bdc1c489d6c)

**Comment by DHstun** [comment]
re-opened https://github.com/Najmul190/Discord-AI-Selfbot/issues/21 *

**Comment by Najmul190** [comment]
You downloaded the latest update right? I just tried it and it seems to work fine

**Comment by DHstun** [comment]
Yeah latest version installed, tried to re-isntall python but still not working, is there any way to fix this?
![изображение_2023-08-13_125932711](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/b2de1970-b69c-4d8e-9c69-85c10c5eb213)

**Comment by DHstun** [comment]
Worked yesterday btw

**Comment by DHstun** [comment]
![изображение_2023-08-13_134716862](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/622aa383-c6be-4981-9b43-d899f13a1e38)
huh? (https://gpt4.xunika.uk) 

the error - Error making the request: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL**('https://gpt4.xunika.uk/api/openai/v1/chat/completions')**

**Comment by DHstun** [comment]
Fixed. I got blocked by https://gpt4.xunika.uk/ (too much requests), if someone needs a fix just enable VPN
