### ISSUE TITLE
[BUG] Bot launches and starts typing

### ISSUE THREAD

**Issue by CSPG305** [Najmul190/Discord-AI-Selfbot#23]
i see no bard cookie error. However it doesnt finish typing it stops and throws the following error in the screenshots
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/104031273/82b473a3-2b06-4658-a25c-57610123a56f)

**Comment by Najmul190** [comment]
I guess your repl.it ip has been blocked from the using the ChatGPT site, there's nothing I can do about it unfortunately
