### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by DHstun** [Najmul190/Discord-AI-Selfbot#24]
**Describe the bug**
13.08.2023 - i was getting blocked by https://gpt4.xunika.uk/ (cloudflare too much requests), i used vpn to fix this
14.08.2023 - vpn does not help anymore even the website shows that im not blocked. i have the same issue https://github.com/Najmul190/Discord-AI-Selfbot/issues/23, running on my main pc not replit
![изображение_2023-08-14_105708123](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/ac1ead78-0f8c-4c7a-af30-51ddfd6fc8bd)

**Additional context**
Seems like i cant just connect to "https://gpt4.xunika.uk/" even im not blocked anymore by cloudflare
![without](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/288afdf0-88dd-493f-bbbc-85ad18ab6b54)
![WITH](https://github.com/Najmul190/Discord-AI-Selfbot/assets/102819104/2c1d34d4-071a-4a93-a51e-5e61cb23ad93)

re-opened https://github.com/Najmul190/Discord-AI-Selfbot/issues/22. Latest update installed.

**Comment by Najmul190** [comment]
Should work now, or at least it does for me as I'm not blocked from the site.
