### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Whitesun123** [Najmul190/Discord-AI-Selfbot#25]
Same issue as #24 

`Error making the request: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://gpt4.xunika.uk/api/openai/v1/chat/completions')
Task exception was never retrieved
future: <Task finished name='Task-27' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /home/runner/Discord-AI-Selfbot/main.py:263> exception=AttributeError("'NoneType' object has no attribute 'splitlines'")>
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Selfbot/main.py", line 266, in generate_response_in_thread
    chunks = split_response(response)
  File "/home/runner/Discord-AI-Selfbot/main.py", line 99, in split_response
    lines = response.splitlines()
AttributeError: 'NoneType' object has no attribute 'splitlines'`

I have just updated the main.py file and still get this issue, I'm hosting the bot on replit.

**Comment by Najmul190** [comment]
Your repls IP may be blocked by the site, as it works fine for me.

**Comment by DHstun** [comment]
try to enable vpn, worked before 4 me

**Comment by Whitesun123** [comment]
After not using the bot for 3 days it now started working again.

**Comment by DHstun** [comment]
kinda weird lmao
