### ISSUE TITLE
[BUG] prybar-python310 not found in $PATH

### ISSUE THREAD

**Issue by SilentSal0** [Najmul190/Discord-AI-Selfbot#28]
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1
Error: prybar-python310 not found in $PATH
repl process died unexpectedly: exit status 1

Getting this error.

**Comment by L7NEG** [comment]
https://ask.replit.com/t/error-prybar-python310-not-found-in-path-cant-stop-console/25754

**Comment by Najmul190** [comment]
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/68229089/5ddedcc3-b040-4d32-8706-fdb40bdb531b)
