### ISSUE TITLE
Who is he??

### ISSUE THREAD

**Issue by nihs269** [Najmul190/Discord-AI-Selfbot#37]
User ID: 181960927321653258

 Username: azekial_khyber#0

 Badges:
 Created: Tue, 17 May 2016 02:47:45 UTC

**Comment by Najmul190** [comment]
just someone i forgot to remove, why does it matter

**Comment by nihs269** [comment]
ok

**Comment by nihs269** [comment]
> just someone i forgot to remove, why does it matter

ok
