### ISSUE TITLE
[BUG] Bot Texting

### ISSUE THREAD

**Issue by Kran03** [Najmul190/Discord-AI-Selfbot#38]
This error pops up when I text the bot, every other feature works

Error making the request: Cannot connect to host free.chatgpt.org.uk:443 ssl:default [Access is denied]
Task exception was never retrieved
future: <Task finished name='Task-21' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\Profile\Discord-AI-Selfbot\main.py:253> exception=AttributeError("'NoneType' object has no attribute 'splitlines'")>
Traceback (most recent call last):
  File "C:\Users\Profile\Discord-AI-Selfbot\main.py", line 256, in generate_response_in_thread
    chunks = split_response(response)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Profile\Discord-AI-Selfbot\main.py", line 95, in split_response
    lines = response.splitlines()
            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'splitlines'

**Comment by Kran03** [comment]
nvm fixed it

**Comment by ivegot0bitches** [comment]
> nvm fixed it

how did you fix it? cant fix mine currently
