### ISSUE TITLE
[BUG] choices = response_data["choices"]

### ISSUE THREAD

**Issue by dhstunn** [Najmul190/Discord-AI-Selfbot#41]
Bug with gpt model, BARD works fine.

GPT model is unable to generate a response, fix please
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/148810162/bc143762-ee2d-489b-9f4c-95b42d52ec66)

**Comment by dhstunn** [comment]
same as #17

**Comment by surelygabriel** [comment]
I also get the same error, despite having the latest version. Mind telling me what you changed to fix the error #17  had?

**Comment by dhstunn** [comment]
> I also get the same error, despite having the latest version. Mind telling me what you changed to fix the error #17 had?

He is not responding anymore but u still can use bard cookie instead of chatgpt.

**Comment by JTMCDev** [comment]
The issue is that the endpoint doesnt allow API requests (as far as I know) you will have to use your own chatgpt key or find an alternative free option (if you do post it here)

**Comment by dhstunn** [comment]
well i will try to make it on bggpt then🙃

**Comment by Najmul190** [comment]
FIXED!
