### ISSUE TITLE
[BUG] it doesn't respond to me

### ISSUE THREAD

**Issue by tikislizfr** [Najmul190/Discord-AI-Selfbot#46]
whenever i try to talk to it it doesn't respond and here is a screenshot of the console
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/114265073/9158ad02-58ea-424f-817d-c1af53976dd0)

**Comment by ivegot0bitches** [comment]
same with me

**Comment by Najmul190** [comment]
FIXED!
