### ISSUE TITLE
Suggestions for Improving AI Integration on Discord

### ISSUE THREAD

**Issue by Delta0S** [Najmul190/Discord-AI-Selfbot#57]
I have a question about the AI. I suggest using the ChatGPT API instead. Sometimes, when I give clear instructions, it doesn’t fully understand them. While it works most of the time, there are moments when it just seems off. Could you consider integrating ChatGPT? If you do, I’d be happy to create a free video guide on setting it up. Also, what happens if there’s a delay in the Discord chat? Would that cause any issues? I’ve noticed that the bot replies too quickly, so I recommend adding a delay to its responses. I’ve tested it a lot, and this change could improve the experience.

**Comment by Najmul190** [comment]
There's no good, free ChatGPT APIs that I can find, so that's why I'm using the Meta one. Delay can easily be added, I just never did as I wanted the bot to be quick but I'll add it soon.

**Comment by jkramer5103** [comment]
I would also Like a Openai Integration, you could add it as a n Option for everybody to use their own API Key, and if no key was enterred, you could still use Meta.

**Comment by Najmul190** [comment]
> I would also Like a Openai Integration, you could add it as a n Option for everybody to use their own API Key, and if no key was enterred, you could still use Meta.

are you willing to lend me your API key for a few uses perchance

**Comment by jkramer5103** [comment]
How can i Direct Message you?

**Comment by Najmul190** [comment]
add me on Discord, my username is `najmul`

**Comment by Najmul190** [comment]
ChatGPT API has now been added!
