### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by TwangyMoney** [Najmul190/Discord-AI-Selfbot#8]
**Describe the bug**
Bot doesn't respond, in DMs or in channels. I did the toggleactive command on a channel, but he still doesn't reply. He has dms set to true and I even used the command to set it to true, he still doesn't respond. He is currently being run on replit.

**To Reproduce**
Simply add it to repl.it, add the secrets, install requirements (basically all the steps on the readme) and then run the program.

**Expected behavior**
Expected for it to speak to me.

**Screenshots**
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/87775970/4af0811c-665d-448c-b131-1d460689fcc9)
![image](https://github.com/Najmul190/Discord-AI-Selfbot/assets/87775970/f307dc1d-2251-4708-8c5f-2cf81b400489)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Here's the full log from console:
WARNING: Skipping discord as it is not installed.
WARNING: Skipping discord.py as it is not installed.
Looking in indexes: https://package-proxy.replit.com/pypi/simple/
Requirement already satisfied: aiohttp in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.8.3)
Requirement already satisfied: aiofiles in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (23.1.0)
Requirement already satisfied: curl_cffi in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (0.5.6)
Requirement already satisfied: fake_useragent in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (1.1.3)
Requirement already satisfied: httpx in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (0.24.1)
Requirement already satisfied: flask in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 6)) (2.2.2)
Requirement already satisfied: asyncio in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (3.4.3)
Requirement already satisfied: python-dotenv in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (1.0.0)
Requirement already satisfied: pyYAML in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (6.0)
Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.28.2)
Requirement already satisfied: pydantic in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (1.10.9)
Requirement already satisfied: langdetect in ./venv/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (1.0.9)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (6.0.4)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (22.2.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (1.3.3)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.10/site-packages (from aiohttp->-r requirements.txt (line 1)) (1.8.2)
Requirement already satisfied: cffi>=1.12.0 in ./venv/lib/python3.10/site-packages (from curl_cffi->-r requirements.txt (line 3)) (1.15.1)
Requirement already satisfied: sniffio in ./venv/lib/python3.10/site-packages (from httpx->-r requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in ./venv/lib/python3.10/site-packages (from httpx->-r requirements.txt (line 5)) (0.17.2)
Requirement already satisfied: certifi in ./venv/lib/python3.10/site-packages (from httpx->-r requirements.txt (line 5)) (2022.12.7)
Requirement already satisfied: idna in ./venv/lib/python3.10/site-packages (from httpx->-r requirements.txt (line 5)) (3.4)
Requirement already satisfied: Werkzeug>=2.2.2 in ./venv/lib/python3.10/site-packages (from flask->-r requirements.txt (line 6)) (2.2.2)
Requirement already satisfied: click>=8.0 in ./venv/lib/python3.10/site-packages (from flask->-r requirements.txt (line 6)) (8.1.3)
Requirement already satisfied: itsdangerous>=2.0 in ./venv/lib/python3.10/site-packages (from flask->-r requirements.txt (line 6)) (2.1.2)
Requirement already satisfied: Jinja2>=3.0 in ./venv/lib/python3.10/site-packages (from flask->-r requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->-r requirements.txt (line 10)) (1.26.14)
Requirement already satisfied: typing-extensions>=4.2.0 in ./venv/lib/python3.10/site-packages (from pydantic->-r requirements.txt (line 11)) (4.6.3)
Requirement already satisfied: six in ./venv/lib/python3.10/site-packages (from langdetect->-r requirements.txt (line 12)) (1.16.0)
Requirement already satisfied: pycparser in ./venv/lib/python3.10/site-packages (from cffi>=1.12.0->curl_cffi->-r requirements.txt (line 3)) (2.21)
Requirement already satisfied: anyio<5.0,>=3.0 in ./venv/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx->-r requirements.txt (line 5)) (3.7.0)
Requirement already satisfied: h11<0.15,>=0.13 in ./venv/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx->-r requirements.txt (line 5)) (0.14.0)
Requirement already satisfied: exceptiongroup in ./venv/lib/python3.10/site-packages (from anyio<5.0,>=3.0->httpcore<0.18.0,>=0.15.0->httpx->-r requirements.txt (line 5)) (1.1.1)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from Jinja2>=3.0->flask->-r requirements.txt (line 6)) (2.1.2)
WARNING: pip is using a content-addressable pool to install files from. This experimental feature is enabled through --use-feature=content-addressable-pool and it is not ready for production.
Looking in indexes: https://package-proxy.replit.com/pypi/simple/
Collecting discord.py-self
  Downloading https://package-proxy.replit.com/pypi/packages/6c/86/7f54e265f2bacb29355d024c8ca9135811591ea5c60dbd57bed001a199f3/discord.py_self-2.0.0-py3-none-any.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 11.4 MB/s 
Collecting discord-protos<1.0.0
  Downloading https://package-proxy.replit.com/pypi/packages/3a/7c/4b9eaf1f85caa5ff93caa948ee47a2fc5be2d2bbd4b60d3f989da84c8140/discord-protos-0.0.2.tar.gz (13 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: aiohttp<4,>=3.7.4 in ./venv/lib/python3.10/site-packages (from discord.py-self) (3.8.3)
Requirement already satisfied: yarl<2.0,>=1.0 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (1.8.2)
Requirement already satisfied: attrs>=17.3.0 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (22.2.0)
Requirement already satisfied: aiosignal>=1.1.2 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (1.3.1)
Requirement already satisfied: frozenlist>=1.1.1 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (4.0.2)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (2.1.1)
Requirement already satisfied: multidict<7.0,>=4.5 in ./venv/lib/python3.10/site-packages (from aiohttp<4,>=3.7.4->discord.py-self) (6.0.4)
Requirement already satisfied: protobuf in ./venv/lib/python3.10/site-packages (from discord-protos<1.0.0->discord.py-self) (4.21.12)
Requirement already satisfied: idna>=2.0 in ./venv/lib/python3.10/site-packages (from yarl<2.0,>=1.0->aiohttp<4,>=3.7.4->discord.py-self) (3.4)
Building wheels for collected packages: discord-protos
  Building wheel for discord-protos (PEP 517) ... done
  Created wheel for discord-protos: filename=discord_protos-0.0.2-py3-none-any.whl size=13958 sha256=bef55744ea8f9c4fbddbdeb6d4714aea06b1f77aff7476dbdcc41b0fda192941
  Stored in directory: /home/runner/.cache/pip/wheels/1c/c8/6e/8b7d59408174a217be68ad9d6f239b025f617cab091d00e0e3
Successfully built discord-protos
WARNING: pip is using a content-addressable pool to install files from. This experimental feature is enabled through --use-feature=content-addressable-pool and it is not ready for production.
Installing collected packages: discord-protos, discord.py-self
Successfully installed discord-protos-0.0.2 discord.py-self-2.0.0
2023-06-21 14:48:40 INFO     discord.client Logging in using static token.
 * Serving Flask app 'keep_alive'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:3000
 * Running on http://172.31.196.33:3000
Press CTRL+C to quit
2023-06-21 14:48:41 INFO     discord.http Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36, build number 206653.
2023-06-21 14:48:42 INFO     discord.gateway Connected to Gateway (Session ID: cd2e7d5f3b27ca76df234b9e1acdef4a).
Vega has connected to Discord!
172.31.196.1 - - [21/Jun/2023 14:48:47] "GET / HTTP/1.1" 200 -
2023-06-21 14:52:11 ERROR    discord.ext.commands.bot Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "pfp" is not found
2023-06-21 14:52:34 ERROR    discord.ext.commands.bot Ignoring exception in command None
discord.ext.commands.errors.CommandNotFound: Command "pfp" is not found
An error occurred while making the request: 400, message='Bad Request', url=URL('https://inferenceengine.vyro.ai/sdprem')
An error occurred while writing the image to file: a bytes-like object is required, not 'NoneType'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0df1c276d0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f0df1bfa8c0>, 11662.966089787)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f0df1c24cd0>
2023-06-21 14:53:16 ERROR    discord.ext.commands.bot Ignoring exception in command imagine
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/Discord-AI-Selfbot/main.py", line 437, in imagine
    file = discord.File(filename, filename="image.png")
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/file.py", line 99, in __init__
    self.fp = open(fp, 'rb')
TypeError: expected str, bytes or os.PathLike object, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: expected str, bytes or os.PathLike object, not NoneType
2023-06-21 14:54:09 ERROR    discord.ext.commands.bot Ignoring exception in command toggleactive
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/runner/Discord-AI-Selfbot/main.py", line 369, in toggleactive
    f"{ctx.channel.mention} has been added to the list of active channels."
AttributeError: 'DMChannel' object has no attribute 'mention'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/home/runner/Discord-AI-Selfbot/venv/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'DMChannel' object has no attribute 'mention'

**Comment by Najmul190** [comment]
weird, seems to work fine for me in channels but i fixed a few aspects of the DM messaging. try remake the repl.it and contact me on discord @najmul if it still doesnt work

**Comment by TwangyMoney** [comment]
Sir, i wanna mention i already did like an hour ago and still same issue

**Comment by TwangyMoney** [comment]
btw could you also mention how exactly it works like where do you send the requests and like how does it work where do the messages we send go
